# Generated by Django 2.2 on 2021-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20210319_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='old dojo'),
        ),
    ]
